name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build:
    name: publish tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Generate Git Tag
        id: generate_tag
        run: |
          VERSION_PREFIX="v"
          VERSION_MAJOR_MINOR="5.0"
          VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
          if [ -z "$VERSION_PATCH" ]; then
            VERSION_PATCH=0
          else
            VERSION_PATCH=$((VERSION_PATCH + 1))
          fi
          NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Push Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: read formula config file
        id: read_formula
        run: |
          url="https://github.com/wswenyue/aklog/archive/${NEW_TAG}.tar.gz"
          sha256=$(wget -O aklog.tar.gz ${url} && shasum -a 256 aklog.tar.gz | cut -d ' ' -f 1)
          echo "url==>${url}" >> $GITHUB_STEP_SUMMARY
          echo "sha256==>${sha256}" >> $GITHUB_STEP_SUMMARY
          rm -rf ./aklog.tar.gz
          en_url=`echo $url |sed 's#\/#\\\/#g'`
          echo "========0=======" >> $GITHUB_STEP_SUMMARY
          #          cat .github/data/aklog.rb >> $GITHUB_STEP_SUMMARY
          echo "========1=======" >> $GITHUB_STEP_SUMMARY
          sed -e "s/#_url_#/${en_url}/g; s/#_sha256_#/${sha256}/g" .github/data/aklog.rb > formula.rb
          echo "========2=======" >> $GITHUB_STEP_SUMMARY
          echo "========3=======" >> $GITHUB_STEP_SUMMARY

      - name: upload new Formula
        uses: actions/upload-artifact@v4
        with:
          name: formula
          path: formula.rb
  #
  #      - name: print formula
  #        run: |
  #          echo "======end======" >> $GITHUB_STEP_SUMMARY
  #  #          echo $formula >> $GITHUB_STEP_SUMMARY
  #  #          echo "============" >> $GITHUB_STEP_SUMMARY

  homebrew:
    name: publish homebrew
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # We generate static HTML, JS, CSS so we need write access to the repo
      pages: write
      id-token: write
      deployments: write
      statuses: write
      actions: write
      checks: read
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v4
        with:
          repository: wswenyue/homebrew-aklog
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          # token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
      - name: Download formula
        uses: actions/download-artifact@v4
        with:
          name: formula
      - shell: bash
        run: |
          echo "save data to aklog.rb"
          cat formula.rb > Formula/aklog.rb
          rm -rf formula.rb
      - name: Commit files
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          ls -alh
          git status
          git commit -a -m "Add changes"
          git push origin master
          echo "succeed."
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          repository: wswenyue/homebrew-aklog
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}
